services:
  kafka:
    image: redpandadata/redpanda:v24.3.6
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 512M
      - --reserve-memory
      - 0M
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://127.0.0.1:9094
    ports:
      - "9094:9092"
      - "9646:9644"

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: personal_backup
      POSTGRES_USER: backup
      POSTGRES_PASSWORD: backup
    ports:
      - "5437:5432"
    volumes:
      - personal-backup-postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6384:6379"

volumes:
  personal-backup-postgres-data:
