services:
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - package-tracker-redis:/data

volumes:
  package-tracker-redis:
