server.port=8107
cache.virtual-nodes=64
cache.replication-factor=2
cache.node-capacity=12
cache.default-ttl-seconds=180
cache.max-ttl-seconds=3600
cache.initial-nodes=cache-a,cache-b,cache-c,cache-d
spring.thymeleaf.cache=false
